import { describe, expect, it } from "vitest";

import fixture from "./data/storm-block-2026-08-08.json";

import {
  type StormDriverSample,
  type StormIndices,
  DPS_JOULES_PER_NT,
  clockAngleDeg,
  drawableRows,
  newellBand,
  newellCoupling,
  ringCurrentEnergyJoules,
  ringCurrentNarrative,
  sampleAt,
  sampleDriverAt,
  stormNarrativeAt,
  stormStripRows,
  stripWindow,
  toSegments,
} from "../src/storm-indices";

/**
 * Driven by the artifact the pipeline actually produces from the live feeds.
 *
 * `tests/data/storm-block-2026-08-08.json` was generated by running
 * `pipeline/storm_indices.py` and `propagated_driver_series` over verbatim
 * NOAA and USGS payloads captured at 2026-08-08T02:41:20Z. Using the real
 * artifact rather than a hand-written one is what makes these tests evidence
 * that the browser can read what the pipeline writes.
 */
const FIXTURE = fixture as unknown as { storm: StormIndices; driverSeries: StormDriverSample[] };

const STORM = FIXTURE.storm;
const DRIVERS = FIXTURE.driverSeries;
const CAPTURED_AT = new Date("2026-08-08T02:41:20Z");

describe("derived quantities, mirrored from the pipeline", () => {
  it("agrees with the published clock angle and coupling on every driver sample", () => {
    // The pipeline computed these in Python and the browser recomputes them in
    // TypeScript at scrubbed times. If the two ever disagree the panel would
    // show one number and the artifact another.
    let checked = 0;
    for (const sample of DRIVERS) {
      if (sample.byNt === null || sample.clockAngleDeg === null) continue;
      expect(clockAngleDeg(sample.byNt, sample.bzGsmNt)).toBeCloseTo(sample.clockAngleDeg, 1);
      expect(newellCoupling(sample.speedKps, sample.byNt, sample.bzGsmNt)!)
        .toBeCloseTo(sample.newellCoupling!, 1);
      checked += 1;
    }
    expect(checked).toBeGreaterThan(200);
  });

  it("uses the same DPS constant the pipeline published", () => {
    expect(DPS_JOULES_PER_NT).toBeCloseTo(STORM.ringCurrent.joulesPerNt, -4);
    expect(ringCurrentEnergyJoules(-100)! / 1e15).toBeCloseTo(3.892, 3);
  });

  it("reports no ring-current energy for a positive Dst", () => {
    expect(ringCurrentEnergyJoules(20.5)).toBe(0);
  });
});

describe("sampling at a scrubbed time", () => {
  it("never reaches forward past the selected instant", () => {
    const early = new Date("2026-08-08T00:30:00Z");
    const sample = sampleAt(STORM.dst.kyoto.series, early, 90);
    expect(sample).not.toBeNull();
    expect(Date.parse(sample!.at)).toBeLessThanOrEqual(early.getTime());
  });

  it("refuses to hold a one-minute trace across an hour-long gap", () => {
    // The modelled Dst is one-minute; asking for a time before its window
    // begins must produce nothing rather than the first available value.
    const wayBack = new Date("2026-08-07T12:00:00Z");
    expect(sampleAt(STORM.dst.modelled.series, wayBack, 10)).toBeNull();
    // But the hourly Kyoto index legitimately holds for its own cadence.
    expect(sampleAt(STORM.dst.kyoto.series, wayBack, 90)).not.toBeNull();
  });

  it("finds the guarded driver sample nearest the selected time", () => {
    const driver = sampleDriverAt(DRIVERS, CAPTURED_AT);
    expect(driver).not.toBeNull();
    expect(Date.parse(driver!.validAt)).toBeLessThanOrEqual(CAPTURED_AT.getTime());
    expect(driver!.subsolarStandoffRe).toBeGreaterThan(8);
  });
});

describe("the narrative at an instant", () => {
  it("carries both sides of the chain and the nowcast error between them", () => {
    const narrative = stormNarrativeAt(STORM, DRIVERS, CAPTURED_AT)!;
    expect(narrative).not.toBeNull();
    expect(narrative.driving).not.toBeNull();
    expect(narrative.driving!.clockAngleDeg).toBeGreaterThanOrEqual(0);
    expect(narrative.driving!.subsolarStandoffRe).toBeGreaterThan(8);
    expect(narrative.responding.modelledNt).not.toBeNull();
    expect(narrative.responding.observedNt).not.toBeNull();
    // The whole point of showing three traces: the nowcast is gradeable.
    expect(narrative.responding.nowcastErrorNt).not.toBeNull();
    expect(Math.abs(narrative.responding.nowcastErrorNt!)).toBeLessThan(60);
  });

  it("reads the live data as a weak southward turning on a quiet day", () => {
    // At 02:41Z on 2026-08-08 the propagated IMF reaching Earth was Bz = -1.11
    // nT with a clock angle of 171 degrees - almost due south, but on a field
    // of only 3.8 nT behind a 255 km/s wind, so the coupling function is 1,732
    // against a published quiet band of about 4,800. This is the case the site
    // will show most of the time, and it is the one a naive clock-angle
    // implementation gets wrong.
    const narrative = stormNarrativeAt(STORM, DRIVERS, CAPTURED_AT)!;
    expect(narrative.driving!.bzGsmNt).toBeLessThan(0);
    expect(narrative.driving!.southward).toBe(true);
    expect(narrative.driving!.clockAngleDeg!).toBeGreaterThan(150);
    expect(narrative.driving!.clockAngleDeg!).toBeLessThan(200);
    expect(narrative.driving!.newellCoupling!).toBeLessThan(4773);
    expect(narrative.driving!.newellBand).toBe("very quiet");
    // Orientation is the switch, not speed: the field is southward and the
    // planet is still quiet, because the field is weak and the wind is slow.
    expect(narrative.phase.label).toBe("quiet");
  });

  it("keeps the northward branch of the clock angle for the newest sample", () => {
    // The newest propagated sample, an hour past the scrubbed instant, had
    // By = -0.67 and Bz = +1.50: clock angle 336 degrees, not 24. Folding the
    // branch would put a northward IMF in the southward quadrant.
    expect(clockAngleDeg(-0.67, 1.5)).toBeCloseTo(335.93, 1);
  });

  it("says nothing rather than something when the drivers are absent", () => {
    const narrative = stormNarrativeAt(STORM, [], CAPTURED_AT)!;
    expect(narrative.driving).toBeNull();
    // The Dst traces are independent of the solar-wind guard and remain.
    expect(narrative.responding.observedNt).not.toBeNull();
  });

  it("returns nothing at all when there is no storm block", () => {
    expect(stormNarrativeAt(null, DRIVERS, CAPTURED_AT)).toBeNull();
  });

  it("bands the coupling against the published ladder", () => {
    const calibration = STORM.derived!.newellCalibration;
    expect(newellBand(0, calibration)).toBe("very quiet");
    expect(newellBand(5000, calibration)).toBe("quiet");
    expect(newellBand(30000, calibration)).toBe("storm");
    expect(newellBand(200000, calibration)).toBe("extreme");
    expect(newellBand(null, calibration)).toBeNull();
  });
});

describe("strip-chart rows", () => {
  const window_ = stripWindow(STORM, CAPTURED_AT, 24);

  it("extends the axis past now, because the nowcast does", () => {
    expect(window_.to).toBeGreaterThan(window_.now);
    const leadMinutes = (window_.to - window_.now) / 60_000;
    expect(leadMinutes).toBeGreaterThan(30);
    expect(leadMinutes).toBeLessThan(120);
  });

  it("orders the rows cause to effect and badges each one separately", () => {
    const narrative = stormNarrativeAt(STORM, DRIVERS, CAPTURED_AT);
    const rows = drawableRows(stormStripRows(STORM, DRIVERS, window_, narrative));
    expect(rows.map((row) => row.key)).toEqual([
      "bz", "clock", "newell", "standoff", "dst", "ring",
    ]);
    // Sharing an axis must not give the rows a common evidence class.
    const badges = new Set(rows.map((row) => row.badge));
    expect(badges.size).toBeGreaterThan(2);
    expect(rows.find((row) => row.key === "bz")!.badge).toBe("observed");
    expect(rows.find((row) => row.key === "standoff")!.badge).toBe("empirical");
    expect(rows.find((row) => row.key === "dst")!.badge).toBe("model + observed");
  });

  it("keeps the three Dst traces as three traces", () => {
    const rows = stormStripRows(STORM, DRIVERS, window_, null);
    const dst = rows.find((row) => row.key === "dst")!;
    expect(dst.traces.map((trace) => trace.kind)).toEqual(["model", "observed", "kyoto"]);
    for (const trace of dst.traces) expect(trace.points.length).toBeGreaterThan(5);
    // Each carries its own joinable spacing, so an hourly index is not
    // shattered and a one-minute index is not welded across an outage.
    const gaps = dst.traces.map((trace) => trace.maximumGapMs);
    expect(gaps[0]).toBeLessThan(gaps[2]!);
  });

  it("drops rows with no data instead of drawing an empty axis", () => {
    const rows = drawableRows(stormStripRows(STORM, [], window_, null));
    expect(rows.map((row) => row.key)).toEqual(["dst", "ring"]);
  });

  it("shows a real 24-hour swing in the boundary and the driving", () => {
    // The live day was quiet, and even so the Shue standoff moved by more than
    // two Earth radii. That is what the panel exists to make visible.
    const rows = stormStripRows(STORM, DRIVERS, window_, null);
    const values = (key: string) =>
      rows.find((row) => row.key === key)!.traces[0]!.points
        .map((point) => point.value)
        .filter((value): value is number => value !== null);
    const standoff = values("standoff");
    expect(Math.max(...standoff) - Math.min(...standoff)).toBeGreaterThan(1.5);
    const bz = values("bz");
    expect(Math.min(...bz)).toBeLessThan(0);
    expect(Math.max(...bz)).toBeGreaterThan(0);
  });
});

describe("gaps stay gaps", () => {
  it("breaks the line rather than bridging a missing sample", () => {
    const points = [
      { t: 0, value: 1 },
      { t: 60_000, value: 2 },
      { t: 120_000, value: null },
      { t: 180_000, value: 4 },
    ];
    const segments = toSegments(points, 90_000);
    expect(segments).toHaveLength(2);
    expect(segments[0]!.map((point) => point.value)).toEqual([1, 2]);
    expect(segments[1]!.map((point) => point.value)).toEqual([4]);
  });

  it("breaks the line when the spacing exceeds the trace's own cadence", () => {
    const points = [
      { t: 0, value: 1 },
      { t: 60_000, value: 2 },
      { t: 3_600_000, value: 3 },
    ];
    expect(toSegments(points, 90_000)).toHaveLength(2);
    // The same points at an hourly tolerance are one continuous line.
    expect(toSegments(points, 2 * 3_600_000)).toHaveLength(1);
  });

  it("produces nothing from an empty or wholly missing series", () => {
    expect(toSegments([], 1000)).toEqual([]);
    expect(toSegments([{ t: 0, value: null }, { t: 1, value: Number.NaN }], 1000)).toEqual([]);
  });
});

describe("making the ring current legible", () => {
  it("gives tangible comparisons and never separates them from the caveat", () => {
    const narrative = ringCurrentNarrative(STORM.ringCurrent, ringCurrentEnergyJoules(-100))!;
    expect(narrative.tangibles).toHaveLength(3);
    expect(narrative.tangibles[0]).toMatch(/megatons/);
    expect(narrative.tangibles[1]).toMatch(/US electricity/);
    expect(narrative.uncertainty).toMatch(/factor of two/);
    expect(narrative.relation).toMatch(/Dessler-Parker-Sckopke/);
    // The composition honesty travels with it: the model fixes 80/20 H+/O+,
    // reality does not.
    expect(narrative.composition.join(" ")).toMatch(/80% H\+ \/ 20% O\+/);
    expect(narrative.composition.join(" ")).toMatch(/Daglis/);
  });

  it("says there is no ring current rather than showing a zero", () => {
    const narrative = ringCurrentNarrative(STORM.ringCurrent, null)!;
    expect(narrative.headline).toMatch(/No ring-current energy|joules/);
  });

  it("scales the comparisons with the storm", () => {
    const moderate = ringCurrentNarrative(STORM.ringCurrent, ringCurrentEnergyJoules(-100))!;
    const great = ringCurrentNarrative(STORM.ringCurrent, ringCurrentEnergyJoules(-600))!;
    const megatons = (text: string) => Number.parseFloat(text);
    expect(megatons(great.tangibles[0]!)).toBeGreaterThan(megatons(moderate.tangibles[0]!) * 5);
  });
});
