#!/usr/bin/env bash
# Release gate for this repository.
#
# No file here -- content or filename -- may name an AI vendor or coding
# assistant. The single, deliberate exception is the Acknowledgments sentence
# carried by the two papers (Markdown drafts, LaTeX sources and built PDFs),
# which is a required disclosure and is whitelisted verbatim below.
#
# Usage:  tools/release_gate.sh [repo-root]
# Exit 0 = clean, exit 1 = at least one disallowed reference. Violations print
# as  path:line: text  so they can be fixed directly.
#
# How each file is read:
#   * text files     -- in full, against the full token list
#   * PDFs           -- via pdftotext, full token list. If pdftotext is missing
#                       the file is reported as NOT SCANNED rather than passed
#                       silently, and the gate fails.
#   * other binaries -- via `strings -n 4`. Compressed and encoded streams throw
#                       up three-letter byte runs at random, so binaries are
#                       matched on the unambiguous tokens plus the realistic
#                       compound forms of the short ones ("gpt-4", "llm-assisted"),
#                       never on a bare three-letter run. Filenames are always
#                       checked against the full list.
#   * this script    -- exempt, since stating the rule requires naming the tokens.
set -u

ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT" || { echo "release_gate: cannot enter $ROOT" >&2; exit 2; }

SELF='./tools/release_gate.sh'

# Case-insensitive ERE. Word boundaries on the short tokens so ordinary English
# does not trip the gate -- "philanthropically" contains "anthropic".
PATTERN='\bclaude|\banthropic\b|\bopenai\b|\bgpt|\bcodex|\bcopilot|generated by ai|\bllms?\b|\blarge language models?\b'

# Applied to extracted strings of non-PDF binaries. See the header.
BIN_PATTERN='\bclaude|\banthropic\b|\bopenai\b|\bcodex|\bcopilot|generated by ai|\blarge language models?\b|\bgpt[-_ ]?[0-9o]|\bllm[-_ ][a-z]'

# Exactly this many whitelisted acknowledgment lines must be found: one per
# paper Markdown draft, one per LaTeX source, one per built PDF. Fewer means
# the required disclosure has gone missing; more means it has spread.
ACK_EXPECTED=6
ACK='large language models to assist with manuscript preparation'
ACK_FILES='
./docs/paper-a-draft-20260921.md
./docs/paper-b-draft-20260921.md
./docs/latex/paper-a/paper-a.tex
./docs/latex/paper-b/paper-b.tex
./docs/latex/paper-a/paper-a.pdf
./docs/latex/paper-b/paper-b.pdf
'

violations=0
ack_seen=0
scanned=0

is_ack_file() {
  case "$ACK_FILES" in *"
$1
"*) return 0 ;; esac
  return 1
}

while IFS= read -r -d '' f; do
  scanned=$((scanned + 1))

  # --- filename check: full token list, every file ---
  if printf '%s' "$f" | grep -qiE "$PATTERN"; then
    printf '%s:0: DISALLOWED FILENAME\n' "$f"
    violations=$((violations + 1))
  fi

  [ "$f" = "$SELF" ] && continue

  # --- content check ---
  pat="$PATTERN"
  case "$f" in
    *.pdf)
      if command -v pdftotext >/dev/null 2>&1; then
        text=$(pdftotext -q "$f" - 2>/dev/null)
      else
        printf '%s:0: NOT SCANNED (pdftotext unavailable)\n' "$f"
        violations=$((violations + 1))
        continue
      fi
      ;;
    *)
      if grep -Iq . "$f" 2>/dev/null; then
        text=$(cat "$f")
      else
        text=$(strings -n 4 "$f" 2>/dev/null)
        pat="$BIN_PATTERN"
      fi
      ;;
  esac

  hits=$(printf '%s\n' "$text" | grep -niE "$pat" 2>/dev/null)
  [ -z "$hits" ] && continue

  while IFS= read -r hit; do
    [ -z "$hit" ] && continue
    if is_ack_file "$f" && printf '%s' "$hit" | grep -qF "$ACK"; then
      ack_seen=$((ack_seen + 1))
      continue
    fi
    printf '%s:%s\n' "$f" "$hit"
    violations=$((violations + 1))
  done <<< "$hits"
done < <(find . -path ./.git -prune -o -type f -print0)

echo "----------------------------------------------------------------------"
echo "files scanned: $scanned"
echo "whitelisted Acknowledgments lines found: $ack_seen (expected $ACK_EXPECTED)"
if [ "$violations" -eq 0 ] && [ "$ack_seen" -eq "$ACK_EXPECTED" ]; then
  echo "RELEASE GATE: PASS -- 0 disallowed references"
  exit 0
fi
[ "$ack_seen" -ne "$ACK_EXPECTED" ] && echo "RELEASE GATE: FAIL -- the Acknowledgments disclosure is not where it should be"
[ "$violations" -gt 0 ] && echo "RELEASE GATE: FAIL -- $violations disallowed reference(s)"
exit 1
