import { factProvenance, learningSources, LAYER_SOURCES, sourceLinks } from "./learning-provenance";
import { evidenceBadge, evidenceGuide, legacyMediaNote, type Evidence } from "./learning-evidence";
import { withLearningContents } from "./learning-sections";
/**
 * One page for every layer.
 *
 * Sean, 2026-08-19, ASKING FOR THE PAGES: "on the learning page we need a page
 * to each of the layers, including the ones we took off." That is a quotation
 * of the request, in the shorthand the two of us use about our own build. It is
 * NOT a model for the voice of the page. It was lifted verbatim into the
 * index's own headline once - "Every layer, including the ones we took off." -
 * and Sean, 2026-08-21: "The term 'Every layer, including the ones we took
 * off.' sounds really, really bad. Like, we don't want to say we took off
 * layers."
 *
 * The set really is complete, retired layers included, and the page says so -
 * but in the paragraph, as a fact about what a reader will find, not in the
 * headline as an announcement about us. Anything quoted in this file from an
 * internal conversation is evidence for a decision; the reader-facing sentence
 * still has to be written.
 *
 * The shape of a layer page is fixed, and it is deliberately short:
 *
 *   1. WHAT IT IS      two sentences, no more. If a picture can say it, the
 *                      picture says it.
 *   2. THE VISUAL      the point of the page. Every one carries an evidence
 *                      chip burned into the video itself as well as printed
 *                      beside it, so the class survives being screenshotted.
 *   3. WHY IT MATTERS  the operational consequence, as numbers, taken from this
 *                      site's own published artifacts and documents wherever one
 *                      exists. No number appears here that is not sourced below.
 *   4. HOW WE KNOW     the instrument or model, and where it stops knowing.
 *
 * EVIDENCE CLASSES. Every number and every visual on these pages carries the
 * class of the WEAKEST claim it rests on. A schematic that quotes three
 * published values is still a schematic. Where a page's video changes class
 * partway through — the ring current's does, from MODEL-DERIVED to OBSERVED —
 * the badge inside the video changes with it, on screen, where it can be seen.
 *
 * THE VIDEOS. Eight are drawn with Manim from the formula named in each
 * caption; one is real observational footage. None of them is generated by an
 * image or video model. That was tried, at cost, and rejected: see the change
 * report for why. They are imported rather than fetched, so Vite hashes them
 * into dist/assets and the deploy carries them the same way it carries the two
 * typefaces — see src/styles.css for the same pattern with the woff2 files.
 *
 * PROPORTION. Sean, 2026-08-21: "the text on all the sections is way too small.
 * The videos are GIANT compared to the text." Measured at 1440 before the fix,
 * the video was the full 1060 px content column and the prose round it was
 * 11 px at 92 characters a line. The type and the video cap now live in
 * src/layer-pages.css, scoped to the `.layer-page` / `.layer-index` wrappers
 * this module emits, because the sizes they override are SHARED with the
 * lessons, events, sources and Data & methods pages.
 *
 * THE NARRATION SLOT. Every video carries an empty, hidden
 * `<div class="layer-narration" data-narration-for="<page id>">` inside its
 * <figcaption>, between the evidence chip and the caption prose — directly
 * under the clip. The id is the same one `data-layer-page` uses and the same
 * one narration/layer-pages.json calls `clip`. Dropping the `hidden` attribute
 * reveals it; a button, an <audio> and a <details> transcript placed inside it
 * inherit the page's reading size with no further stylesheet. The audio files
 * belong in media/narration-layers/. This module does not build any of that.
 *
 * Static markup only, like src/content.ts and src/connections.ts. The one thing
 * this module cannot do for itself is bind its own navigation: the [data-view]
 * sweep in main.ts runs once at start-up, so the buttons below are bound by
 * ExplorerApp.mountLayerPages() after this markup is injected.
 */

import thermosphereClip from "./media/thermosphere.mp4";
import ionosphereClip from "./media/ionosphere.mp4";
import plasmasphereClip from "./media/plasmasphere.mp4";
import beltsClip from "./media/radiation-belts.mp4";
import ringCurrentClip from "./media/ring-current.mp4";
import magnetopauseClip from "./media/magnetopause.mp4";
import solarWindClip from "./media/solar-wind.mp4";
import peakSurfacesClip from "./media/peak-surfaces.mp4";
import dRegionClip from "./media/d-region.mp4";
import footprintClip from "./media/ground-track-footprint.mp4";

import thermospherePoster from "./media/thermosphere.webp";
import ionospherePoster from "./media/ionosphere.webp";
import plasmaspherePoster from "./media/plasmasphere.webp";
import beltsPoster from "./media/radiation-belts.webp";
import ringCurrentPoster from "./media/ring-current.webp";
import magnetopausePoster from "./media/magnetopause.webp";
import solarWindPoster from "./media/solar-wind.webp";
import peakSurfacesPoster from "./media/peak-surfaces.webp";
import dRegionPoster from "./media/d-region.webp";
import footprintPoster from "./media/ground-track-footprint.webp";

import "./layer-pages.css";

import { substormChainPageView } from "./substorm-chain-page";

/** The chip classes that already have a treatment in src/styles.css. */

type Fact = { value: string; caption: string };
type Row = { term: string; detail: string };

type LayerPage = {
  id: string;
  index: string;
  name: string;
  extent: string;
  /**
   * What kind of page this is. "layer" pages are about a thing in the
   * environment; "how" pages are about a thing this site DRAWS, which is a
   * different claim and belongs in its own group rather than numbered in with
   * the physics.
   */
  kind?: "layer" | "how" | "process";
  /** Where it lives now: on the globe, or retired to this page. */
  place: "globe" | "chart" | "retired";
  evidence: Evidence;
  evidenceLabel: string;
  /** Two sentences. This is enforced by a test, not by good intentions. */
  lead: string;
  video: {
    src: string;
    /**
     * A representative frame, not the first one.
     *
     * With preload="none" a browser draws nothing at all until the visitor
     * presses play, and the first frame of most of these is an empty header.
     * A still from the middle of the argument says what the video is about
     * before it costs anyone a download.
     */
    poster: string;
    /**
     * Carries a spoken track, so it must not be muted and must not loop.
     *
     * Every other clip here is a silent diagram that reads without sound, and
     * loops harmlessly. One does not: the coronagraph loop is ambiguous on its
     * own, so it carries a line in Sean's own cloned voice — and a narrated clip
     * that restarts its first sentence every fifteen seconds is worse than a
     * silent one.
     */
    narrated?: boolean;
    evidence: Evidence;
    evidenceLabel: string;
    /** What the moving picture is, and — as importantly — what it is not. */
    caption: string;
  };
  /** The operational consequence, in numbers. */
  facts: Fact[];
  /** The instrument or model, and its limits. */
  rows: Row[];
  /** The sentence that says what this page must never be read as. */
  doNotInfer: string;
  /**
   * A page that renders its own body instead of the standard
   * lead-video-facts-methods block.
   *
   * Exactly one page needs this and it is the reason the field exists: the
   * substorm chain is about a SEQUENCE rather than a thing, so it is six
   * stages and two animations rather than one video and four numbers. It is
   * registered here rather than given its own route so that the existing
   * `data-layer-page` binding carries it for free, and so it appears in the
   * same index a reader is already looking at.
   */
  body?: () => string;
};

const PAGES: LayerPage[] = [
  {
    id: "thermosphere",
    index: "01",
    name: "Thermosphere",
    extent: "120 – 1,000 km",
    place: "globe",
    evidence: "model",
    evidenceLabel: "Operational forecast, with an empirical field elsewhere",
    // CORRECTNESS AUDIT 2026-09-04 — "five orders of magnitude" was wrong, and
    // wrong against numbers printed two lines below it. The three published WAM
    // values in this page's own video caption run 1.67e-8 to 3.07e-15 kg m^-3,
    // a ratio of 5.4e6, which is 6.7 decades. src/thermosphere-volume.ts says so
    // in as many words — "the field falls 6.7 decades across that range" — and
    // the clip's own axis is drawn from log10 -15 to -8. The old sentence
    // understated the thinning by a factor of about 55 on the one page whose
    // entire subject is how fast the air thins.
    lead:
      "The thermosphere is the last air a satellite ever touches — neutral gas, mostly nitrogen, oxygen and helium, thinning by nearly seven orders of magnitude between 120 and 1,000 km. It is not the ionosphere: it is the gas the ionosphere lives inside, and it is the part that actually causes drag.",
    video: {
      src: thermosphereClip,
      poster: thermospherePoster,
      evidence: "schematic",
      evidenceLabel: "Schematic · quiet-time model reference points",
      caption:
        "A schematic density profile drawn through the three published WAM quiet-time values this site ships — 1.67×10⁻⁸ kg m⁻³ at 120 km, 2.50×10⁻¹² at 420 km, 3.07×10⁻¹⁵ at 1,000 km. Those three points are marked; everything between them is log-linear interpolation and is drawn as a thin dashed line to say so. The moving highlight only guides reading through those points; it does not depict changing air. No frame of it is a measurement of any particular moment.",
    },
    facts: [
      { value: "7.3×10⁻⁷ m s⁻²", caption: "Model · fixed worked example, not a clock-driven value: density 2.50×10⁻¹² kg m⁻³ at 420 km, circular orbital speed, and ballistic coefficient 100 kg m⁻² (mass divided by the product of drag coefficient and area). Atmospheric rotation and winds are neglected." },
      { value: "2.27×", caption: "the density at 400 km at the Gannon storm peak against three days earlier — WAM global mean" },
      { value: "4.7×", caption: "the spread in density at 420 km right round the globe at one instant, so drag depends on where in the orbit you are" },
      { value: "38 of 49", caption: "Starlink spacecraft from the February 2022 launch that reentered after a storm nobody would have called severe · Historical events" },
    ],
    rows: [
      { term: "The product", detail: "NOAA's Whole Atmosphere Model neutral density, republished on this site's own five-minute cycle — but one WAM release covers about twelve hours of a timeline that runs 48 hours back and 72 forward." },
      { term: "The empirical coverage", detail: "NRLMSIS 2.1 covers the other nine tenths, on the same grid and the same nineteen levels, evaluated hour by hour from NOAA's 10.7 cm flux and from ap — the linear-scale twin of Kp, the 0-to-9 planetary disturbance index — converted out of the Kp series this site already draws, through Bartels' standard table. The two are never blended: the badge on the card names which one drew the hour you are looking at, and it changes as you scrub across the boundary." },
      { term: "Why the empirical one exists everywhere", detail: "An empirical model is a published fit driven by indices rather than a forecast integrated from an initial condition, so it can be evaluated at any instant its drivers reach — and because ap is one of those drivers, it responds to a storm. That is the whole reason to prefer it over showing nothing: watch the air thicken and the drag rise as Kp climbs, across the same days the Kp chart on this site is drawing." },
      { term: "Where it is weakest", detail: "Storms. A CCMC assessment across 151 storms found the MSIS family underestimates density by 20–30% through the main and recovery phases. <a href=\"https://pure.tudelft.nl/ws/portalfiles/portal/160425445/Space_Weather_2023_He_Comparison_of_Empirical_and_Theoretical_Models_of_the_Thermospheric_Density_Enhancement_During.pdf\">He et al. (2023)</a> is starker still: for one event NRLMSIS 2.0 gave about 25% enhancement where Swarm-A measured +110% and GRACE-FO +120%, and six models disagreed with each other by up to 70%." },
      // CORRECTNESS AUDIT 2026-09-04 — the extent line and the lead both handed a
      // reader 120 km as though it were the bottom of the thermosphere. It is the
      // bottom of NOAA's published WAM field (THERMOSPHERE_VOLUME_ALTITUDE_KM.low).
      // The reference profile starts at 120 km; this row distinguishes that
      // data floor from the physical boundary.
      { term: "Where 120 km comes from", detail: "The published field, not the atmosphere. NOAA's WAM levels begin at 120 km, so that is where this page's extent begins and where the profile in the video begins. The thermosphere itself begins lower — at the mesopause, somewhere near 85 to 90 km — and this site draws no neutral density at all between there and 120 km." },
      { term: "The other swing nobody budgets for", detail: "Before any storm at all, the density at 400 km changes by a factor of 12.8 between solar minimum and solar maximum. At 200 km it is only a factor of 2, and at 100 km it is 1.06 — the whole effect lives up where the spacecraft are." },
      { term: "One measurement that ran the wrong way", detail: "Swarm-C measured a 23% density DEPLETION on 12 May 2024 against 9 May, in the middle of the largest storm in twenty years and despite enhanced EUV — because nitric-oxide cooling flux hit an all-time high of 11.84 erg cm⁻² s⁻¹. The thermosphere does not only inflate." },
    ],
    doNotInfer:
      "Do not read a density here as a drag prediction for a named spacecraft. Drag needs that spacecraft's own area, mass, attitude and drag coefficient, and this site publishes none of them.",
  },
  {
    id: "ionosphere",
    index: "02",
    name: "Ionosphere",
    extent: "60 – 2,655 km",
    place: "globe",
    evidence: "forecast",
    evidenceLabel: "Physics-model forecast, with an empirical D region",
    // CORRECTNESS AUDIT 2026-09-04 — 2,655 km is the top of the model column this
    // site integrates (src/ionosphere-density-volume.ts, `high: 2655`), not a
    // physical top: the topside thins into the plasmasphere with no edge in it.
    // The video caption already said the two extents were "this site's own"; the
    // lead quoted the same number to four figures as if it were the sky.
    lead:
      "The ionosphere is not a layer of the atmosphere — it is the fraction of it that solar ultraviolet has knocked apart into ions and free electrons. It starts below the thermosphere at 60 km and is still going far above it at 2,655 km, where this site\u2019s model column stops rather than where the plasma does: the two overlap, and neither contains the other.",
    video: {
      src: ionosphereClip,
      poster: ionospherePoster,
      evidence: "schematic",
      evidenceLabel: "Schematic",
      caption:
        "A schematic Chapman-style profile: it shows where the D, E, F1 and F2 regions sit and how they change between day and night, and it draws no measured density at all. The two extents on the left — thermosphere 120–1,000 km, ionosphere 60–2,655 km — are this site's own, taken from the code that draws them.",
    },
    facts: [
      { value: "16 cm", caption: "of apparent GPS L1 range error per TECU — one TEC unit, 10¹⁶ electrons in a one-square-metre column — before any dual-frequency correction" },
      { value: "8.98×10⁻⁶ √Nₑ", caption: "foF2 in MHz — the highest frequency the F2 peak reflects straight back down, from the peak density alone" },
      { value: "D absorbs, E and F reflect", caption: "the same ionosphere, opposite effects, which is why one disturbance can kill HF and leave UHF untouched" },
      { value: "90 – 2,655 km", caption: "the column this site actually integrates, so its TEC and its range error both run somewhat low" },
    ],
    rows: [
      { term: "The product", detail: "NOAA WAM-IPE, a coupled whole-atmosphere and ionosphere-plasmasphere forecast, four cycles a day. Below 90 km the volume is an explicitly empirical Wait–Spies D region instead, because WAM-IPE does not resolve it." },
      { term: "The gap that is left empty on purpose", detail: "85 to 90 km is drawn by neither model. The empirical D region stops at 85 and the physics model starts at 90, and rather than interpolate across the seam the site leaves it blank." },
      { term: "What TEC can and cannot do", detail: "Total electron content is the electrons in a column, integrated. It is a real assimilated measurement and it is the right number for a range error. It cannot locate the D, E, F1 and F2 layers vertically — a column total has no height in it — which is why TEC is drawn on the column it totals rather than at an altitude of its own." },
      { term: "What this site will not derive", detail: "Scintillation. The published fields carry no irregularity spectrum, so no scintillation index can honestly be computed from them, and none is." },
    ],
    doNotInfer:
      "Do not read the profile as a sounding. It is the shape of the four regions, not a measurement of the electron density above any place at any time.",
  },
  {
    id: "plasmasphere",
    index: "03",
    name: "Plasmasphere",
    // CORRECTNESS AUDIT 2026-09-04 — this read "L 2 – 6" while the page's own
    // headline fact puts the quiet plasmapause at 7.2 Re, outside the range the
    // page declared for itself. The published DGCPM grid runs L 2 to 8:
    // pipeline/plasmasphere_dgcpm.py PUBLISHED_L_MAXIMUM = 8.0, and the artifact's
    // grid.lValues confirm it. Six was neither the model's bound nor the
    // plasmasphere's.
    extent: "L 2 – 8",
    place: "chart",
    evidence: "model",
    evidenceLabel: "Physics simulation on measured Kp",
    lead:
      "The plasmasphere is cold, dense plasma that has leaked up out of the ionosphere and been trapped, corotating with the Earth out to a boundary called the plasmapause. It occupies the same space as the ring current and the inner radiation belt while being thousands of times denser and thousands of times colder than either.",
    video: {
      src: plasmasphereClip,
      poster: plasmaspherePoster,
      evidence: "model",
      evidenceLabel: "Model, evaluated exactly",
      caption:
        "The boundary is the last closed equipotential — the outermost drift path that still closes around the Earth — of the standard Volland–Stern picture, corotation plus convection, with the convection amplitude taken from the same Maynard & Chen form this site computes elsewhere. When Kp is turned up on screen the boundary moves in because the arithmetic moves it. It is not a spacecraft crossing, and no in-situ plasmapause measurement exists in any feed this site reads.",
    },
    facts: [
      { value: "7.2 → 3.3 Rᴇ", caption: "where that arithmetic puts the plasmapause as Kp goes from 2 to 8" },
      { value: "2,319 km", caption: "how far the midnight boundary actually travelled across one quiet 25-frame window — L 4.14 to 4.51 — with Kp never above 2.89" },
      { value: "50 cm⁻³", caption: "the contour this site calls the boundary, interpolated in log density between shells" },
      // CORRECTNESS AUDIT 2026-09-04 — this used to end "so the outer belt reaches
      // inward toward geostationary", which runs the wrong way. Geostationary is
      // L 6.6, already INSIDE the outer belt's L 3–7 as the next page draws it; a
      // belt reaching inward across a cleared slot moves toward the GNSS shells
      // near L 4.2 and on into the slot at L 2–3, which is exactly where CIRBE
      // found the new belt after Gannon. The old wording put the operational
      // consequence on the wrong constellation.
      { value: "the slot fills in", caption: "erode the plasmasphere and the hiss that sweeps the slot region clear goes with it, so the outer belt reaches inward across the GNSS shells near L 4.2 and on into the slot itself" },
    ],
    rows: [
      { term: "The product", detail: "A DGCPM simulation driven by measured Kp — the three-hourly 0-to-9 planetary disturbance index. It fills toward an empirical ceiling over days, drains on the night side, and shows the dusk-side plume peeling off when convection strengthens. The ring current is computed in its convection field, which is why the simulation is still fetched and still runs even though it no longer draws anything on the globe." },
      { term: "Why it left the globe", detail: "It was drawn as a cloud of grains, and it looked invented. A picture that looks invented cannot be rescued by a caption saying it is not, so on 2026-08-18 the cloud was removed and the physics was kept. Not every legend identity is a rail layer." },
      { term: "Where it went", detail: "To a plan-view boundary chart at the FOOT of Current conditions, on the same page as the Kp that squeezes it. It sits below NOAA\u2019s own products rather than above them, because it is a simulation and they are the measurement, and because nothing is decided by it. Noon at the top, midnight at the bottom, dusk to the left. A second curve traced from the steepest density gradient is published next to the boundary as an independent check on the same frame." },
      // Added 2026-09-04 with the extent fix above: an extent field is read as the
      // layer's edges, and these are the artifact's.
      { term: "What L 2 and L 8 are", detail: "The published grid\u2019s edges, not the plasmasphere\u2019s. Cold plasma is continuous with the topside ionosphere below L 2, and the simulation is integrated out to L 9 so the outer shells can be flushed properly even though only L 2 to 8 is published and drawn." },
      { term: "The measurement that decided the container", detail: "At L 2 the modelled density varies by 1.16× across all 24 hours of magnetic local time and 1.10× between frames — about 1% of a colour ramp spanning 1 to 3,000 cm⁻³. There was nothing for a filled volume to show. The boundary, by contrast, moved 2,319 km on a quiet day." },
    ],
    doNotInfer:
      "Do not read the boundary as an observed crossing. It is a contour in a simulation driven by a measured index, which is a different kind of thing from a spacecraft that flew through it.",
  },
  {
    id: "radiation-belts",
    index: "04",
    name: "Radiation belts",
    extent: "inner L 1.2 – 2 · outer L 3 – 7",
    place: "globe",
    evidence: "model",
    evidenceLabel: "Coupled pitch-resolved electron model",
    lead:
      "Two nested regions of trapped particles: an inner belt of protons at L 1.2 to 2 that is essentially always there, and an outer belt of electrons at L 3 to 7 that can change by a factor of a hundred in a day. Between them sits the slot, swept nearly clear by plasmaspheric hiss.",
    video: {
      src: beltsClip,
      poster: beltsPoster,
      evidence: "composite",
      evidenceLabel: "Schematic cross-section; model field map",
      caption:
        "The belt cross-section and the single field line are schematic — every curve is the dipole relation r = L cos²λ at the conventional L ranges, and no flux value is drawn. The world map at the end is not schematic: it is IGRF-14 total field at 500 km, contoured, over the same public-domain Natural Earth 1:110m coastline the site itself draws. The composite contains a schematic cross-section and a model field map; neither is a measured global flux distribution.",
    },
    facts: [
      { value: "1,000 pfu", caption: "NOAA's ≥2 MeV integral electron flux alert level — pfu is particle flux units, particles per cm² per second per steradian — where internal charging of spacecraft dielectrics becomes an operational concern" },
      { value: "18.3 µT", caption: "the weakest total field anywhere at 500 km — over the South Atlantic, where the inner belt reaches lowest and most LEO single-event upsets are collected" },
      { value: "≈ 610 km", caption: "how far the geomagnetic dipole sits from the centre of the Earth · a belt drawn about geographic latitude is a belt with the anomaly edited out" },
      { value: "L 2.5 – 3.5", caption: "where CIRBE found a new belt of 1.3–5 MeV electrons after the Gannon storm, in the slot that is supposed to be empty" },
    ],
    rows: [
      { term: "The product", detail: "The NOAA/NASA Radiation Belt Environment model: a phase-space solution on a grid of 51 radial by 48 magnetic local time by 12 energy by 12 pitch angle — the angle between a particle's motion and the field line, which decides where it mirrors — published at four energies — 88 keV, 453 keV, 1.35 MeV and 2.32 MeV." },
      { term: "The three motions it solves for", detail: "Gyration around the field line in microseconds to milliseconds; bounce between magnetic mirror points in tenths of a second to seconds; drift all the way round the Earth in minutes to hours. Electrons drift east and ions west, which is why the drift is also a current — see the ring current." },
      { term: "What is displayed and what is held back", detail: "The window is L ≥ 1.2 Rᴇ and flux ≥ 10¹, though the model grid reaches inward to 1.0157 Rᴇ. The colour ramp is fixed at 10¹ to 10⁵·⁵ in every energy view so two energies can be compared by eye. If no frame covers the selected time the geometry is hidden entirely rather than a stale frame being held." },
      { term: "Why the anomaly is where it is", detail: "A trapped particle mirrors where the field reaches a fixed strength. The dipole is tilted about 11° from the spin axis and displaced roughly 550 km from the Earth's centre, so on one side of the planet that mirror height is far lower — down into low Earth orbit over the South Atlantic. The map in the video is the real IGRF field, not the dipole approximation, because the eccentric dipole puts the minimum about 2,000 km too far north." },
    ],
    doNotInfer:
      "Do not read a flux here as a dose. Dose needs shielding, spectrum, geometry and time in the environment, and this site models none of them.",
  },
  {
    id: "ring-current",
    index: "05",
    name: "Ring current",
    extent: "L 2 – 7",
    place: "globe",
    evidence: "model",
    evidenceLabel: "Model-derived · the shape is not measured",
    lead:
      "Ions of 10 to 200 keV trapped between about L 2 and L 7 drift westward around the Earth while electrons drift east; both contribute to a westward current of several million amperes. This site draws computed drift geometry; spacecraft also observe ring-current particles in situ.",
    video: {
      src: ringCurrentClip,
      poster: ringCurrentPoster,
      evidence: "composite",
      evidenceLabel: "Model geometry, then observed Dst",
      caption:
        "This clip changes evidence class on screen. This site's drift geometry and current loop are model-derived, not measured shapes. Its observed input is Dst, a ground-magnetometer index influenced by multiple current systems, not a complete direct measurement of the ring. Spacecraft also measure ring-current particles in situ; this display does not ingest those measurements. The limitation is this site's data, not what science can observe.",
    },
    facts: [
      { value: "Dst", caption: "Observed · a surface-field disturbance index from four low-latitude ground magnetometers, recorded since 1957; influenced by the ring current and other current systems" },
      { value: "a factor of two", caption: "how well the Dessler–Parker–Sckopke relation turns that depression into the total energy in the trapped ions" },
      { value: "10 keV → 80 keV", caption: "what an ion gains being carried from L 8 in to L 4 · energy goes as L⁻³, so transport is energisation" },
      { value: "80% H⁺ / 20% O⁺", caption: "typical composition — and the oxygen fraction, which comes from our own ionosphere, rises in the big storms" },
    ],
    rows: [
      { term: "What this site observes", detail: "This display uses Dst: one ground index with no radial, altitude, local-time or composition map. It is influenced by multiple current systems. In-situ instruments such as the Van Allen Probes' <a href=\"https://doi.org/10.1007/s11214-013-9965-x\">RBSPICE</a> measure particle energies and composition along spacecraft paths. This site does not ingest those particle measurements; their absence here is a data limitation of this display." },
      { term: "What this site models", detail: "The shapes drawn here. The drift paths, the Alfvén layer — the last drift path that still closes around the Earth, which is the drawn region's outer edge — the inner and outer edges and the volume drawn on the globe all come from integrating drift in a published convection field. The geometry is computed rather than sketched, but computed is still not measured." },
      { term: "Why its field opposes the Earth's", detail: "A westward current makes a magnetic field that, inside the loop, points south. The Earth's own field at low-latitude ground points north. So while the ring current is strong, magnetometers all round the low-latitude Earth read low, and Dst goes negative." },
      // CORRECTNESS AUDIT 2026-09-04 — two different clocks had been merged into
      // one sentence ("400×, one hour of drift per second"). They are not the same
      // number and they are not the same animation:
      // RING_CURRENT_DRIFT_REPLAY.physicalSecondsPerDisplaySecond = 400 and
      // RING_CURRENT_FORMATION.physicalSecondsPerDisplaySecond = 3600, whose own
      // docstring reads "Different from RING_CURRENT_DRIFT_REPLAY's 400x, and
      // deliberately". 400× is 6 min 40 s a second; an hour a second is 3,600×.
      // The "two and a half orders of magnitude" in the same row is log10(400),
      // which is the half of the old sentence that was right.
      { term: "The playback rate", detail: "The drift replay runs at 400× — six minutes and forty seconds of drift in every second of screen time. The ring-formation loop beside it runs at 3,600×, an hour a second, because a ring current is built over a storm's main phase rather than in one lap. Both are display choices and both are stated on the layer, because a viewer who read the drift as real time would have the ion's drift period wrong by two and a half orders of magnitude." },
    ],
    doNotInfer:
      "Do not read the drawn ring as the location of the current. Dst constrains how much energy is in it, not where.",
  },
  {
    id: "magnetopause",
    index: "06",
    name: "Magnetopause and bow shock",
    // CORRECTNESS AUDIT 2026-09-04 — the compressed bound read 6 Rᴇ while the fact
    // card below quotes the same arithmetic reaching 5.6. One was a rounded memory
    // of the other.
    extent: "nose 5.6 – 13.5 Rᴇ · shock ≈ 13 Rᴇ",
    place: "globe",
    evidence: "empirical",
    evidenceLabel: "Live-input empirical boundary",
    // CORRECTNESS AUDIT 2026-09-04 — "the bow shock stands about 13 Earth radii
    // sunward of it" put the shock 13 Rᴇ BEYOND the magnetopause, near 23 Rᴇ.
    // Thirteen is its distance from Earth. This page's own extent says
    // "shock ≈ 13 Rᴇ"; its own methods row reports 13.25 Rᴇ against a 10.25 Rᴇ
    // magnetopause on the same quiet frame; and the clip draws the arc labelled
    // "bow shock = 13 Rᴇ" just outside a magnetopause drawn at about 10. The gap
    // between the two surfaces is a few Earth radii, not thirteen.
    lead:
      "The magnetopause is where the solar wind's pressure balances the Earth's magnetic field — the outer wall of the magnetosphere, and the line between being shielded and not being shielded. The bow shock stands a few Earth radii further out — about 13 from the centre of the Earth on a quiet day, against about 10 for the magnetopause — where the wind slows abruptly because it is arriving faster than any wave that could warn it.",
    video: {
      src: magnetopauseClip,
      poster: magnetopausePoster,
      evidence: "empirical",
      evidenceLabel: "Empirical, evaluated exactly",
      caption:
        "The surface is Shue et al. (1998), the same empirical model the site draws, evaluated at each driver state shown. The standoff walking inward is that formula being computed at real solar-wind values, not an animator's idea of what compressed looks like. The bow shock is a conic of the right family at the right distance and nothing more, and the badge says so.",
    },
    facts: [
      { value: "13.5 → 5.6 Rᴇ", caption: "where the arithmetic puts the subsolar standoff between a very quiet day and Gannon-class driving" },
      { value: "6.6 Rᴇ", caption: "geostationary orbit · in severe events the boundary crosses inside it, and a spacecraft there is in the solar wind" },
      { value: "≈ 6 hours", caption: "how long the dayside boundary spent below geostationary during the Gannon storm, 10–11 May 2024 · Tulasi Ram 2024" },
      { value: "17,230", caption: "spacecraft boundary crossings behind the Nguyen 2022 fit · this is a curve fitted to where the boundary was actually found" },
    ],
    rows: [
      { term: "The model", detail: "r(θ) = r₀[2/(1+cos θ)]^α, with r₀ = [10.22 + 1.29 tanh(0.184(Bz + 8.14))] · Pdyn^(−1/6.6) and α = (0.58 − 0.007 Bz)[1 + 0.024 ln Pdyn]. Two measured numbers from L1 go in — dynamic pressure and the north-south field component — and a surface comes out." },
      { term: "How well it agrees with the physics model", detail: "On a quiet frame the site's own check put the modelled current layer at 10.25 Rᴇ against Shue's 10.61 Rᴇ — a difference of 0.36 Rᴇ, or 3.4%. The bow shock came out at 13.25 Rᴇ." },
      { term: "When it refuses", detail: "If the calibration returns a standoff outside 4 to 18 Rᴇ, or a flaring parameter outside 0.2 to 1.1, the site does not draw it. It falls back to the plain empirical Shue surface from L1 and says which one you are looking at." },
      { term: "A figure this site withdrew", detail: "An earlier version quoted a compression to 3.7–5.0 Rᴇ with no source behind it. It was retracted on 2026-08-08 and replaced with the two published measurements that do exist: Tulasi Ram (2024) for the six hours below geostationary, and Fu et al. (2025) for crossings measured from beyond 10 Rᴇ down to about 5." },
    ],
    doNotInfer:
      "Do not read the drawn surface as the boundary's instantaneous position. It is an empirical fit driven by an upstream measurement propagated by a model step, and the real boundary ripples, folds and moves faster than the fit can follow.",
  },
  {
    id: "solar-wind",
    index: "07",
    name: "Solar wind",
    extent: "measured at L1 · 1.5 million km upstream",
    place: "globe",
    evidence: "observed",
    evidenceLabel: "Observed at L1, propagated by a model step",
    lead:
      "A continuous outflow of plasma from the Sun's corona, dragging the interplanetary magnetic field along with it at 300 to 800 kilometres a second. Everything else on this site is downstream of it.",
    video: {
      src: solarWindClip,
      poster: solarWindPoster,
      narrated: true,
      evidence: "observed",
      evidenceLabel: "Observed · SOHO/LASCO C3",
      caption:
        "Twenty-four hours of real coronagraph frames from SOHO/LASCO C3 on 2026-08-18, at the cadence the instrument published, with no frame interpolated and no recolouring. The bright spokes are coronal streamers, and the solar wind is leaving along every one of them. The dark diagonal is the pylon holding the occulting disk, and the specks are cosmic rays hitting the detector; neither has been cleaned out. Courtesy ESA and NASA. Turn the sound on: this one is narrated, in Sean's own voice.",
    },
    facts: [
      { value: "4.4 – 6.4 min", caption: "measured latency of the L1 feed behind the wall clock, before NOAA's propagation to Earth arrival adds a model step of its own" },
      { value: "1.6726×10⁻⁶ n V²", caption: "dynamic pressure in nPa · this is the number that sets the magnetopause standoff" },
      { value: "southward Bz", caption: "one component of one vector decides whether a fast wind couples to the magnetosphere at all, or slides past it" },
      { value: "2.57 h", caption: "how far ahead of L1 STEREO-A at 0.956 AU — astronomical units; Earth's distance from the Sun is 1 — saw one shock, and it would have forecast the severity to within 8%" },
    ],
    rows: [
      { term: "The product", detail: "NOAA SWPC real-time solar wind. The two files this site reads carry every L1 monitor SWPC is receiving, not only the one it has nominated active — on 2026-08-08 that was SOLAR1, ACE and IMAP, three independent platforms at a 60-second median cadence each." },
      { term: "Two times, on purpose", detail: "Every row carries an L1 observation time and a propagated Earth-arrival time, and they are different. The first is when an instrument a million and a half kilometres away saw something; the second is a calculation about when it gets here." },
      { term: "Why three monitors matter", detail: "Wilkerson et al. (2026) documented one L1 monitor reading 475 km s⁻¹ and 2 cm⁻³ while another read 770 to 1,000 km s⁻¹ and 16 to 29 cm⁻³ — with the quality flag clean on both, throughout. A single monitor is a reading, not a consensus, and this site publishes nothing that has not cleared a corroboration guard." },
      { term: "What happens when the guard fires", detail: "The plotted history is truncated at the fault onset and the derived quantities — dynamic pressure, and the magnetopause that depends on it — are withheld rather than carried forward from the last healthy row." },
    ],
    doNotInfer:
      "Do not read an L1 reading as conditions at Earth. It is one point measurement of a structure far wider than the spacecraft, propagated by an assumption about how that structure is oriented.",
  },
  {
    id: "peak-surfaces",
    index: "08",
    name: "Ionospheric peak surfaces",
    extent: "E, F1 and F2 peak heights",
    place: "retired",
    evidence: "forecast",
    evidenceLabel: "WAM-IPE forecast · the surfaces are retired, the statistics remain",
    lead:
      "Three smooth surfaces, one each for the height of the E, F1 and F2 electron-density maxima, lifted off the globe like relief on a map. They were removed because they drew themselves on a height curve nobody else on the globe was using.",
    video: {
      src: peakSurfacesClip,
      poster: peakSurfacesPoster,
      evidence: "schematic",
      evidenceLabel: "Schematic",
      caption:
        "Both curves in this one are the literal display transforms from the code that drew them: 28·ln(1 + h/350) for the shared radial ruler every other layer uses, and 18·ln(1 + h/350) for the curve these three surfaces used instead — before their heights were multiplied by eight so the relief would read.",
    },
    facts: [
      { value: "hmF2 is an altitude", caption: "the height of the F2 density maximum — not the top of a layer, and not its bottom" },
      { value: "foF2 is a frequency", caption: "the highest that peak reflects straight back down, and it comes from the peak density alone" },
      { value: "two curves, one globe", caption: "everything else — satellites, footprints, belts, boundaries — was placed by the shared ruler; these three were not" },
      { value: "the numbers survived", caption: "the share of columns where a distinct E or F1 maximum resolves, and the mean F2 peak height, are still reported on the ionosphere card" },
    ],
    rows: [
      { term: "What went wrong", detail: "A private height curve plus an eightfold vertical exaggeration put a spacecraft and the density peak it was flying through in visibly different places on the same picture. A viewer reading the globe would have concluded the satellite was well above the F2 layer. It was inside it." },
      { term: "Why it took so long to notice", detail: "Because it looked right. Both choices were defensible on their own — a shared ruler for distance, an exaggeration so a smooth surface has visible relief — and neither is wrong until they share a frame. This is the general lesson the page exists for: a layer that lifts itself onto a private height curve will disagree with everything drawn on the shared one, and it will look convincing while it does." },
      { term: "The second reason", detail: "Once the site drew a full ionospheric density volume, three isolated peak surfaces stood in front of the shell they were standing in for. Their contours of equal height also read as a topographic map of the ground, which is a different thing entirely." },
      { term: "What replaced them", detail: "A click-anywhere probe that reports the column over one place — foF2, hmF2, the maximum usable frequency for a stated path, vertical TEC and the GNSS L1 range error that follows from it — as numbers, where a number cannot be misread as a place." },
    ],
    doNotInfer:
      "Do not treat the probe as an ionosonde. It reads a model column, not a sounding, and the maximum usable frequency it quotes uses a flat-Earth secant law that overstates long paths.",
  },
  {
    id: "d-region",
    index: "09",
    name: "D-region absorption",
    extent: "60 – 90 km",
    place: "globe",
    evidence: "empirical",
    evidenceLabel: "Empirical nowcast",
    lead:
      "The bottom of the ionosphere is the only part of it that takes energy out of a radio wave instead of bending it. Down here the air is still thick enough that a free electron collides with a neutral before it can finish one turn of the wave, and the wave's energy becomes heat.",
    video: {
      src: dRegionClip,
      poster: dRegionPoster,
      evidence: "empirical",
      evidenceLabel: "Empirical, evaluated exactly",
      caption:
        "The absorption curves are NOAA's own documented D-RAP scaling — (HAF ÷ f)^1.5 dB on a vertical two-pass path — evaluated exactly, and the site computes the same number for its map. The reference heights are the ones its empirical Wait–Spies D region uses: about 70 km by day, about 84 km at night.",
    },
    facts: [
      { value: "(HAF ÷ f)^1.5", caption: "absorption in dB · the highest affected frequency is the one number D-RAP publishes per cell, and everything else is arithmetic from it" },
      { value: "×8", caption: "more absorption at 5 MHz than at 20 MHz for the same disturbance, which is why a shortwave circuit dies while a UHF link over the same sky never notices" },
      // CORRECTNESS AUDIT 2026-09-04 — HAF is the HIGHEST affected frequency, which
      // is NOAA's term and this site's own everywhere else (src/drap.ts "1 dB HAF";
      // src/content.ts "the highest frequency expected to lose at least 1 dB").
      // This page defined it correctly in the fact above and then renamed it
      // "maximum affected frequency" here and in the methods row below. The 1 dB
      // definition is also why "nothing is touched at all" was too strong: below a
      // 3 MHz HAF the band still absorbs, just under a decibel of it.
      { value: "3 – 30 MHz", caption: "the HF band · quiet means the modelled highest affected frequency is below 3 MHz, so nothing in the band loses even the one decibel the index is defined at" },
      { value: "70 → 53 km", caption: "how far the absorbing layer drops under an X45 flare — into denser air, where the collision rate is higher still" },
    ],
    rows: [
      { term: "The product", detail: "NOAA's D-Region Absorption Prediction, on a 2° latitude by 4° longitude grid at 0.1 MHz resolution. Exact frames only — no interpolation between them — and a frame is held for at most twelve minutes before the layer goes empty rather than stale." },
      { term: "Why a flare does this", detail: "X-rays reach the daylit hemisphere in about eight minutes and ionise deeper than sunlight ever does, so the absorbing layer moves down into denser air. The whole sunlit half of the planet is affected at once, and it recovers on the flare's timescale — minutes to hours — not on anyone's operational one." },
      { term: "What the site's own statistic means", detail: "The card quotes absorption at 5 MHz computed from the highest affected frequency anywhere on the map. That is a worst-cell figure for one frequency on a vertical path. It is not the absorption on any particular radio link, and a real link needs its own geometry, frequency and path length." },
      { term: "How far back it goes", detail: "The NCEI archive holds this product from September 2009, at roughly 60 MB a day, so a past event can be replayed against the same product that was published at the time." },
    ],
    doNotInfer:
      "Do not read this as a propagation prediction. It says how much a disturbance takes out of a vertical two-pass path at one frequency; it does not tell you whether your circuit closes.",
  },
  {
    id: "ground-track-footprint",
    index: "HOW WE SHOW IT",
    name: "Ground track and footprint",
    extent: "the two lines drawn around a satellite",
    kind: "how",
    place: "globe",
    evidence: "model",
    evidenceLabel: "Geometry computed on a propagated ephemeris",
    lead:
      "The two lines drawn around a selected satellite are its ground track — the path of the point directly beneath it — and its footprint, the circle inside which it is above the horizon. Both are geometry computed from a propagated ephemeris, and the second is the most over-read object on the map.",
    video: {
      src: footprintClip,
      poster: footprintPoster,
      evidence: "schematic",
      evidenceLabel: "Schematic",
      caption:
        "A generic circular orbit at 500 km and 51.6° inclination, over the same public-domain Natural Earth 1:110m coastline the site itself draws. The footprint rings come out of footprintAngularRadius() in src/orbit.ts — the same equation that draws the circle on the globe. No real spacecraft is shown and no ephemeris is quoted.",
    },
    facts: [
      { value: "23.7° west", caption: "how far each successive pass lands, because the Earth turned that far during one 94-minute revolution" },
      // CORRECTNESS AUDIT 2026-09-04 — "and nothing else sets it" / "simply the
      // inclination" is true only below 90°. A retrograde orbit tops out at
      // 180° − i, and this site draws them: src/satellite-fundamentals.ts puts
      // sun-synchronous at 98.19° at 700 km, and a track at 98.19° reaches 81.81°,
      // not 98°. Sun-synchronous is the commonest LEO there is, so the unqualified
      // rule was wrong about a large share of the catalogue on the globe.
      { value: "± the inclination", caption: "the highest latitude a ground track ever reaches — the inclination itself below 90°, and 180° minus it above, so a sun-synchronous orbit at 98.2° tops out at 81.8°" },
      { value: "22.0° → 14.0°", caption: "the footprint half-angle at 500 km as the mask goes from 0° to 10° — about 41% of the area survives" },
      { value: "line of sight only", caption: "the edge is where the spacecraft sits on the horizon · not coverage, not an antenna pattern, not a comms range" },
    ],
    rows: [
      // Same audit: "a plane that stays put in inertial space" and "walks westward
      // by exactly the angle the planet rotated" both ignore nodal regression,
      // which src/satellite-fundamentals.ts explains two pages away as the thing
      // sun-synchronous orbits are built on. Hedged rather than removed — the
      // idealisation is still the right way to introduce the westward walk.
      { term: "What a ground track is", detail: "The moving point on the surface directly beneath the spacecraft. The orbit itself is a plane that stays very nearly put in inertial space — it does precess, slowly, and that slow precession is the whole trick a sun-synchronous orbit is built on — while the Earth turns underneath it, so the track walks westward by about the angle the planet rotated during one revolution." },
      { term: "The latitude limit", detail: "That is why it looks like a sine wave that never quite closes, and why the highest latitude it touches is set by the inclination and nothing else: the inclination itself for a prograde orbit, and 180° minus it for a retrograde one." },
      { term: "What the circle is", detail: "The horizon. λ = arccos((Rₑ ÷ (Rₑ + h)) · cos ε) − ε, which is footprintAngularRadius() in src/orbit.ts character for character. Inside the ring there is an unobstructed straight line from the ground to the spacecraft; outside it the Earth is in the way. At a 0° mask the site draws the tangent horizon on the WGS-84 ellipsoid rather than a spherical small circle, so the real ring is very slightly out of round." },
      { term: "Why an operator raises the mask", detail: "At one degree above the horizon a signal grazes terrain and buildings, arrives together with its own reflections off both, and crosses the longest slant path through the atmosphere it ever will. Raising the mask to 5° or 10° throws that geometry away and buys link margin — and pays for it in footprint area, which is the trade the three options exist to let you see." },
      { term: "What it cannot tell you", detail: "Whether a link closes. Antenna gain and pattern, pointing and attitude, transmit power, receiver noise figure, data rate, polarisation, rain fade and interference are all absent from this site, so a footprint here answers exactly one question — is there a line of sight at the chosen elevation — and refuses every other one." },
    ],
    doNotInfer:
      "Do not read the footprint edge as a coverage boundary. It is the horizon at the chosen mask; whether anything can actually be received anywhere inside it depends on hardware this site does not model.",
  },
  {
    id: "substorm-chain",
    index: "THE CHAIN",
    name: "Where the aurora and the ring current come from",
    extent: "solar wind to both ends of one injection",
    kind: "process",
    place: "globe",
    evidence: "composite",
    evidenceLabel: "Measured timing, empirical geometry, schematic animations — each labelled where it is used",
    lead:
      "The aurora and the ring current are not two things that happen to correlate — they are one injection seen at two radii, and this page follows it from the solar wind to both ends. It also puts the four plasma populations beside each other, because two of them are constantly confused for each other and they sit at opposite ends of the same chain.",
    video: {
      src: "",
      poster: "",
      evidence: "schematic",
      evidenceLabel: "Schematic",
      caption: "",
    },
    facts: [],
    rows: [],
    doNotInfer: "",
    body: substormChainPageView,
  },
];

export const LAYER_PAGE_IDS = PAGES.map((page) => page.id);

/**
 * What this route actually renders, by group.
 *
 * The weather track's door into it said "Ten pages, one per layer" while
 * eleven rendered, because the sentence was a hand-written copy of a fact this
 * array already holds. It is counted now, on both sides of the door.
 */
export const LAYER_PAGE_COUNTS = {
  total: PAGES.length,
  layers: PAGES.filter((page) => page.kind !== "how" && page.kind !== "process").length,
  how: PAGES.filter((page) => page.kind === "how").length,
  process: PAGES.filter((page) => page.kind === "process").length,
};

const PLACE_NOTE: Record<LayerPage["place"], string> = {
  globe: "Drawn on the globe",
  chart: "Retired from the globe · lives as a chart",
  retired: "Retired 2026-08-19 · kept here",
};

/**
 * The chip says the CLASS, in one word. The sentence beside it says what that
 * class means for this particular layer.
 *
 * This is the shape statusKey() already uses on the Data & methods page, and it
 * exists because .layer-status is 8 px monospace: a chip reading "PHYSICS-MODEL
 * FORECAST, WITH AN EMPIRICAL D REGION" is not a chip, it is a paragraph with a
 * border round it, and the one word a reader needs is lost inside it.
 */
function chip(evidence: Evidence, label: string): string {
  // The note says what the class MEANS here. Six of the ten pages label an
  // illustration "Illustration" and a schematic "Schematic", which at reading
  // size prints the same word twice in a row with a box round the first one.
  const note = label.trim().toUpperCase() === evidence.toUpperCase()
    ? ""
    : `<small class="layer-status-note">${label}</small>`;
  return `${evidenceBadge(evidence)}${note}`;
}

function factCells(facts: Fact[], page: string): string {
  return `<div class="processing-facts">${facts
    .map((fact, index) => `<article><strong>${fact.value}</strong><span>${fact.caption}</span>${factProvenance(page, index)}</article>`)
    .join("")}</div>`;
}

function methodRows(rows: Row[], doNotInfer: string, page: string): string {
  const body = rows
    .map((row) => `<div><dt>${row.term}</dt><dd>${row.detail}<div class="method-citation">Related sources and calculation notes: ${sourceLinks(LAYER_SOURCES[page] ?? [], true)}</div></dd></div>`)
    .join("");
  return `<dl>${body}<div><dt>Do not infer</dt><dd>${doNotInfer}</dd></div></dl>`;
}

/**
 * The index: one card per page, in declaration order, which is Earth-outward —
 * thermosphere, ionosphere, plasmasphere, belts, ring current, magnetopause,
 * solar wind — then the chain, then the two pages about a drawing decision.
 *
 * This comment used to claim the cards were sorted "in the order the energy
 * arrives rather than the order the code declares them". They are not and never
 * were: the function renders PAGES as declared, and energy order would put the
 * solar wind first. Whether the route should instead be renumbered Sun-inward
 * is an open question for the owner; what the comment may not do is describe an
 * order the code does not implement.
 */
export function layerPagesIndexView(): string {
  const layers = PAGES.filter((page) => page.kind !== "how" && page.kind !== "process");
  const how = PAGES.filter((page) => page.kind === "how");
  const process = PAGES.filter((page) => page.kind === "process");
  return `
    <div class="layer-index">
    <header class="content-hero">
      <p class="eyebrow">LEARNING TRACK 03 · THE LAYERS</p>
      <h1>One page for every layer.</h1>
      <p>What it is, why an operator cares, and how we know — with the picture doing most of the work. Two of these no longer draw anything on the globe; their pages say why, because the reason is worth more than the layer was.</p>
      <p>In this dipole picture, L labels a whole field line by its equatorial distance from Earth's centre, in Earth radii. L&nbsp;4 reaches 4 Rᴇ from the centre, about 3 Rᴇ above the equatorial surface. Radius from the centre and altitude above the surface differ by one Earth radius.</p>
    </header>
    <div class="lesson-grid layer-index-grid">${layers.map(indexCard).join("")}</div>
    <aside class="teaching-callout"><strong>Every visual here carries its class</strong>The chip is burned into the video as well as printed beside it, so it survives being screenshotted. Where a video changes class partway through, the chip changes with it, on screen.</aside>
    <section class="method-section">
      <div class="method-section-head">
        <span class="section-kicker">THE CHAIN</span>
        <h2>Not a layer — a sequence.</h2>
        <p>Every page above is about a thing. This one is about what happens, in order, and it is where the four populations stop being four unrelated pictures.</p>
      </div>
      <div class="lesson-grid layer-index-grid">${process.map(indexCard).join("")}</div>
    </section>
    <section class="method-section">
      <div class="method-section-head">
        <span class="section-kicker">HOW WE SHOW IT</span>
        <h2>Not a layer — a drawing decision.</h2>
        <p>These pages are about what this site puts on the screen and what that mark does and does not claim. They matter most where a drawing is easy to read as more than it is.</p>
      </div>
      <div class="lesson-grid layer-index-grid">${how.map(indexCard).join("")}</div>
    </section>
    </div>
  `;
}

/** One card on the index. Identical for both groups; only the heading differs. */
function indexCard(page: LayerPage): string {
  const badge = page.kind === "how" ? "HOW WE SHOW IT" : page.kind === "process" ? "THE CHAIN" : `LAYER ${page.index}`;
  return `
      <article class="lesson-card layer-index-card">
        <span class="section-kicker">${badge} · ${PLACE_NOTE[page.place]}</span>
        <h2>${page.name}</h2>
        <p class="layer-index-extent">${page.extent} ${chip(page.evidence, page.evidenceLabel)}</p>
        <p>${page.lead.split(". ")[0]}.</p>
        <button type="button" class="link-button" data-layer-page="${page.id}">Open ${page.name.toLowerCase()} →</button>
      </article>`;
}

/** One layer's page. Unknown ids fall back to the index rather than an error. */
export function layerPageView(id: string): string {
  const page = PAGES.find((candidate) => candidate.id === id);
  if (!page) return layerPagesIndexView();
  // A page that owns its own shape renders it. See LayerPage.body.
  if (page.body) return withLearningContents(`<div class="layer-page">${page.body()}${evidenceGuide()}${learningSources(LAYER_SOURCES[id] ?? [])}</div>`, `layer-${id}`);
  return withLearningContents(`
    <div class="layer-page">
    <button type="button" class="link-button layer-page-back" data-layer-index>← All layers</button>
    <header class="content-hero layer-page-hero">
      <p class="eyebrow">${page.kind === "how" ? "HOW WE SHOW IT" : `LAYER ${page.index}`} · ${page.extent} · ${PLACE_NOTE[page.place]}</p>
      <h1>${page.name}</h1>
      <p>${page.lead}</p>
    </header>
    ${evidenceGuide()}

    <figure class="layer-figure">
      <div class="learning-video-scroll" tabindex="0" role="group" aria-label="Video; scroll sideways when enlarged"><video
        class="layer-video"
        src="${page.video.src}"
        controls
        ${page.video.narrated ? "" : "muted loop"}
        playsinline
        preload="none"
        poster="${page.video.poster}"
        aria-label="${page.name}: ${page.video.evidenceLabel}${page.video.narrated ? ", narrated" : ""}"
      ></video></div>
      <button type="button" class="figure-full-size" data-video-enlarge aria-pressed="false">Enlarge video to original size</button>
      <a class="figure-full-size" href="${page.video.poster}" target="_blank" rel="noopener">Open full-size still (new tab)</a>
      <figcaption class="layer-figcaption">
        <p class="layer-evidence">${chip(page.video.evidence, page.video.evidenceLabel)}</p>
        <div class="layer-narration" data-narration-for="${page.id}" hidden></div>
        <p class="layer-caption-text">${page.video.caption}</p>
        ${legacyMediaNote()}
      </figcaption>
    </figure>

    <section class="method-section">
      <div class="method-section-head">
        <span class="section-kicker">WHY AN OPERATOR CARES</span>
        <h2>The consequence, in numbers.</h2>
      </div>
      ${factCells(page.facts, page.id)}
    </section>

    <section class="method-section">
      <div class="method-section-head">
        <span class="section-kicker">HOW WE KNOW</span>
        <h2>The instrument or the model, and where it stops.</h2>
      </div>
      <div class="method-grid layer-page-methods">
        <details class="method-card" open>
          <summary>
            ${chip(page.evidence, page.evidenceLabel)}
            <strong>${page.name}</strong>
            <small>${page.extent}</small>
          </summary>
          <div class="method-card-body">${methodRows(page.rows, page.doNotInfer, page.id)}</div>
        </details>
      </div>
    </section>
    ${learningSources(LAYER_SOURCES[id] ?? [])}
    </div>
  `, `layer-${id}`);
}
