import { evidenceBadge, legacyMediaNote } from "./learning-evidence";
import { sourceLinks, type SourceId } from "./learning-provenance";
/**
 * The mechanism library: six short animations of how the thing actually works.
 *
 * A graphic carries a mechanism better than a paragraph does. These are the
 * six places where that bites hardest — the steps the Learn track had been
 * asserting in words because no camera has ever filmed them and no instrument
 * returns them as a picture.
 *
 * WHAT THEY ARE, AND WHAT THEY ARE NOT. Every one is drawn with Manim from the
 * geometry or the formula named on the frame. None of them is generated by an
 * image or video model, and none of them is data. They are `schematic` in this
 * site's own vocabulary — "drawn to explain a shape, not to report a value" —
 * and that word is burned into the bottom-left corner of every frame as well as
 * printed in the figcaption, so the class survives being screenshotted or
 * downloaded. Nobody mistakes a labelled vector diagram for a photograph, which
 * is exactly why this genre is safe where generated video is not.
 *
 * WHERE THE NUMBERS COME FROM. A schematic may still carry real numbers, and
 * three of these do. Each such figure names its source here and on the frame:
 * the eccentric-dipole offset is this repository's own arithmetic in
 * src/eccentric-dipole.ts, the Chapman curve is Chapman's 1931 production
 * function evaluated live rather than traced, and the orbital speeds and
 * periods are circular-orbit arithmetic on mu = 398 600 km^3/s^2.
 *
 * TYPOGRAPHY AND COLOUR. The frames use the site's own two typefaces — the
 * exact woff2 files in src/fonts, converted to TTF for Pango — and the palette
 * tokens from src/styles.css. Nothing here is Manim's default blue-on-black.
 *
 * NARRATION. Each clip carries a voice track, muxed into the mp4 rather than
 * served as a parallel mp3 the page would have to keep in sync. It is Sean's
 * own professionally cloned voice through tools/narrate.py, and every line was
 * proved by transcribing the rendered audio back and comparing it to the
 * script. The rule the writing follows is the one thing worth knowing about
 * it: the voice says the point the caption is making, extends it with what the
 * caption had no room for, and picks up the previous line's last idea BY NAME.
 * Thirty-six lines over six and a half minutes of picture, and the voice is on
 * 78 to 87 percent of every clip.
 *
 * THE OPPOSITE RULE USED TO BE WRITTEN HERE and it is retired. It read: the
 * captions are burned into the frame and are good, so the voice never reads
 * them; where there is nothing to add it says nothing; the rest is silence on
 * purpose. It was followed exactly, and it produced fifteen lines for
 * seventy-nine caption beats - speech on 18 to 37 percent of each clip, with
 * the voice first arriving 40.8 s into a 79.1 s clip. Sean watched one and
 * reported his voice missing from the videos. Nothing was broken; the design
 * was wrong. Do not reinstate it: if a beat has nothing worth saying, the
 * answer is a shorter clip, not a silent one.
 *
 * The captions stay regardless - they are the accessibility floor for a deaf
 * reader, they are what makes a clip work with the sound off, and they survive
 * a screenshot because they are burned in. The spoken words are ALSO carried
 * here as `narration` and printed as a closed transcript under each figure,
 * because everything the voice adds is by construction not on the frame.
 *
 * The clips are no longer `muted` and no longer `loop`: a muted narration is
 * not a narration, and a voice track that restarts forever is an irritation
 * rather than a feature. They stay `controls` + `preload="none"`, so nothing is
 * fetched and nothing is heard until the reader presses play.
 *
 * PAGE WEIGHT. Every video is `preload="none"`, so a visit to a page carrying
 * one of these downloads the poster and nothing else until the reader presses
 * play. Sources are under tools/mechanism-animations/.
 */

/**
 * Media under `media/mechanisms/`, resolved the way src/event-replay.ts
 * resolves `media/` — a `new URL` against import.meta.url, which Vite turns
 * into a hashed emit under dist/assets. That matters: deploy/web.Dockerfile
 * copies dist/assets and names every other file explicitly, so an asset that
 * does not go through the bundler is not served at all.
 */
import narrationScript from "../narration/mechanisms.json";
import { countWordCap } from "./count-words";
import narrationAlignment from "../tools/mechanism-animations/narration-alignment.json";
import "./mechanism-animations.css";

const clip = (stem: string) => new URL(`../media/mechanisms/${stem}.mp4`, import.meta.url).href;
const captions = (stem: string) => new URL(`../media/mechanisms/${stem}.vtt`, import.meta.url).href;
const poster = (stem: string) => new URL(`../media/mechanisms/${stem}.jpg`, import.meta.url).href;

export type MechanismAnimation = {
  id: string;
  index: string;
  /** Short title, as it reads on the frame. */
  title: string;
  /** The one-line question the piece answers. */
  question: string;
  /** Two sentences. Anything longer belongs in the animation. */
  lead: string;
  /** Composite when an observed trace accompanies the schematic motion. */
  evidence: "schematic" | "composite";
  evidenceLabel: string;
  /** Runtime, mm:ss. */
  runtime: string;
  /** Named sources for any real number the animation carries. Empty is honest. */
  sources: string[];
  /** File stem under media/mechanisms/; expects <stem>.mp4 and <stem>.jpg. */
  stem: string;
};

/**
 * THE TRANSCRIPT IS DERIVED, NOT TRANSCRIBED.
 *
 * This used to be a `narration: string[]` field on each entry below, hand-copied
 * from narration/mechanisms.json. On 2026-08-27 the clips went from fifteen
 * spoken lines to forty-four and the copy stayed at fifteen, so for as long as
 * that lasted a reader who cannot hear was being given a third of what a
 * hearing reader got -- silently, and with the page still looking correct.
 * That is the exact failure the transcript exists to prevent.
 *
 * So the words come from the script the audio was rendered from, and the ORDER
 * comes from narration-alignment.json, which is the muxer's own record of what
 * it placed where. Neither can drift from the audio without the build changing.
 */
const SPOKEN_TEXT = new Map<string, string>(
  (narrationScript as { lines: { id: string; text: string }[] }).lines
    .map((line) => [line.id, line.text] as const),
);

const NARRATION_BY_STEM = new Map<string, string[]>(
  (narrationAlignment as { stem: string; lines: { id: string }[] }[]).map((clip) => [
    clip.stem,
    clip.lines.map((placed) => SPOKEN_TEXT.get(placed.id)).filter((t): t is string => !!t),
  ]),
);

/** The spoken lines for one clip, in the order they are spoken. */
export function mechanismNarration(stem: string): string[] {
  return NARRATION_BY_STEM.get(stem) ?? [];
}

export const MECHANISM_ANIMATIONS: MechanismAnimation[] = [
  {
    id: "dayside-reconnection",
    index: "01",
    title: "How the wind gets in",
    question: "Why is southward Bz the number everyone watches?",
    lead:
      "Two magnetic fields pointing opposite ways are pressed together at the nose of the magnetosphere until the field breaks and rejoins across the join. The animation follows one opened field line from the nose, over the poles, into the tail, and back again — the Dungey cycle.",
    evidence: "schematic",
    evidenceLabel: "Schematic · not to scale",
    runtime: "1:27",
    sources: [],
    stem: "dayside-reconnection",
  },
  {
    id: "chapman-layer",
    index: "02",
    title: "Why the ionosphere has a peak",
    question: "Why is there an E layer at 110 km rather than ionisation all the way down?",
    lead:
      "Ionising light is strongest at the top and is used up on the way down; air thickens downward. Their product has to peak in between, and that peak is a Chapman layer — which is also why the peak climbs and weakens as the Sun goes down, and why D and E collapse after dark while F2 does not.",
    evidence: "schematic",
    evidenceLabel: "Schematic · Chapman 1931",
    runtime: "1:09",
    sources: [
      "Chapman, S. (1931), Proc. Phys. Soc. 43, 26 — the production function is evaluated live in the scene, not traced by hand. The scale height (28 km) and reference altitude (105 km) are illustrative round numbers and the frame says so.",
    ],
    stem: "chapman-layer",
  },
  {
    id: "hf-skip-blackout",
    index: "03",
    title: "The skip, the MUF, and the blackout",
    question: "Why is the far station loud while the near one is silent — and why does a flare kill the low end first?",
    lead:
      "One hop off the F2 layer, the skip zone it leaves behind, and the highest frequency that still comes back — the maximum usable frequency, the MUF. Then a flare ionises the D region, absorption rises fastest at the bottom of the band, and the lowest usable frequency — the LUF, the floor — climbs until it meets the ceiling and the window shuts.",
    evidence: "schematic",
    evidenceLabel: "Schematic · vertical scale exaggerated",
    runtime: "1:19",
    sources: [
      "Layer heights (D 80 km, E 110 km, F2 300 km) are drawn to scale against each other; the horizontal distance is compressed and the ray paths are illustrative. The site draws the real thing as a nowcast on the D-region HF absorption layer, from NOAA D-RAP.",
    ],
    stem: "hf-skip-blackout",
  },
  {
    id: "trapped-motion",
    index: "04",
    title: "Three motions, and one current",
    question: "Why is the ring current a current at all?",
    lead:
      "A trapped particle gyrates in milliseconds, bounces between mirror points in seconds, and drifts around the Earth in hours. Ions drift west and electrons drift east, which does not cancel — it adds, into the one westward ring whose field at the ground is what Dst measures.",
    evidence: "composite",
    evidenceLabel: "Schematic motion; observed Kyoto Dst at the end",
    runtime: "1:11",
    sources: [
      "The drift paths are drawn as circles. Real drift shells are pulled out of round by convection and their shape depends on the particle's energy; the explorer's inner-magnetosphere layer is where those boundaries are computed. This animation deliberately asserts no local-time asymmetry.",
      "WHAT CIRCLING DOES NOT COVER. The frame says circling a field line never carries a particle to another one, which is true of the gyration and is deliberately narrow. Particles do cross field lines, and this clip's own third motion is the example: drifting right round the planet in hours is motion across the field, as is the sheetward lean on the tail leg in the explorer's magnetosphere layer.",
      "Gradient and curvature drift walk a particle onto neighbouring lines, and where the plasma is frozen to the field the whole flux tube moves and the particle goes with it \u2014 tied to the line as it spirals, carried across as the line travels. All of it is slower than the spiralling, which is why the three motions barely touch each other.",
      "The Dst trace at the end is the one measured object in the library, badged MEASUREMENT on the frame to separate it from everything else in the piece, which is drawn. It is 120 hourly points of final Dst from the World Data Centre for Geomagnetism, Kyoto, covering the Halloween storm of 2003 \u2014 28 October to 2 November, minimum \u2212383 nT at 30 October 22 UT.",
      "The points are read out of this site's own published halloween-2003 replay, the same series the historical-events page draws, and are plotted corner-to-corner: no spline runs between two measurements, because a smooth curve through hourly samples draws excursions that were never recorded.",
    ],
    stem: "trapped-motion",
  },
  {
    id: "eccentric-dipole-saa",
    index: "05",
    title: "The South Atlantic Anomaly is geometry",
    question: "Why is there a hole in the shielding over Brazil?",
    lead:
      "There is no hole. The best-fit dipole sits 610 km from the Earth's centre, so a surface of equal field strength is centred on the dipole rather than on the planet — 1 520 km up on one side and 300 km up on the other, exactly twice the offset apart.",
    evidence: "schematic",
    evidenceLabel: "Schematic · eccentric dipole, IGRF-13",
    runtime: "1:00",
    sources: [
      "Offset 610 km toward 22.7°N 134.7°E, tilt 9.1°, evaluated for 2026.6 by this repository's own arithmetic in src/eccentric-dipole.ts: IGRF-13 degree-1 and degree-2 Gauss coefficients through Fraser-Smith (1987), Rev. Geophys. 25, 1. The antipode of that direction is 22.7°S 45.3°W, in the South Atlantic off Brazil.",
      "An eccentric dipole is still a dipole. It reproduces where the anomaly is, not its exact shape, and it is not the full IGRF field.",
      "The equal-field surface is DRAWN as a circle and a real one is not spherical: a dipole's field at a fixed distance is twice as strong over the poles as over the equator, so the true surface is squashed. What the piece claims is the OFFSET, which is what puts the weak patch over Brazil; the circle is the schematic that carries it. The caption on the frame says the surface rides off centre with the dipole, and stops there.",
    ],
    stem: "eccentric-dipole-saa",
  },
  {
    id: "drag-orbit-decay",
    index: "06",
    title: "Drag makes it go faster",
    question: "How does a force that opposes the motion end up speeding the spacecraft up?",
    lead:
      "Drag takes energy out of the orbit, the orbit drops, and the height it gives up is worth twice what drag removed — so the difference has nowhere to go but into speed. What an operator notices first is not the altitude but the shorter period, and the along-track error that grows with every revolution.",
    evidence: "schematic",
    evidenceLabel: "Schematic · circular-orbit arithmetic",
    runtime: "2:10",
    sources: [
      "400 km → 7 669 m/s and 92.6 min; 300 km → 7 726 m/s and 90.5 min. Circular-orbit arithmetic on μ = 398 600 km³/s² and an equatorial radius of 6 378 km, computed rather than recalled.",
      "The numbers are to scale and the drawing is not. A 400 km orbit is 6 per cent wider than the Earth and the fall to 300 km shrinks it by 1.5 per cent; on the frame the orbit is drawn twice the Earth's radius and the drop takes a fifth off it, because a truthful 1.5 per cent would be invisible. The readout is where the sizes are reported.",
    ],
    stem: "drag-orbit-decay",
  },
];

/**
 * The library's own size, in clips and in seconds.
 *
 * The weather index's mechanisms door carried "6 clips · 6 min 32 s" as
 * hand-written copy. On 2026-08-27 the clips were re-rendered longer — the
 * narration went from fifteen spoken lines to forty-four — and the door did not
 * move, so for as long as that lasted it under-reported its own library by
 * forty seconds. Correcting the constant would go stale again on the next
 * re-render, so the door reads these instead.
 */
export const MECHANISM_LIBRARY_SECONDS = MECHANISM_ANIMATIONS.reduce((total, m) => {
  // "mm:ss", per MechanismAnimation.runtime. A malformed entry propagates NaN
  // rather than being coerced to zero: a door that quietly under-counts its own
  // library is the exact failure this constant exists to end.
  const parts = m.runtime.split(":");
  return total + Number(parts[0]) * 60 + Number(parts[1]);
}, 0);

/** The total runtime as a door prints it: "7 min 12 s". */
export function mechanismLibraryRuntime(): string {
  const minutes = Math.floor(MECHANISM_LIBRARY_SECONDS / 60);
  return `${minutes} min ${MECHANISM_LIBRARY_SECONDS % 60} s`;
}

const byId = new Map(MECHANISM_ANIMATIONS.map((m) => [m.id, m]));

/** Look one up, for a page that wants to embed a single figure. */
export function mechanismAnimation(id: string): MechanismAnimation | undefined {
  return byId.get(id);
}

/**
 * One figure, in the markup the layer pages already use, so it inherits
 * `.layer-figure` / `.layer-video` / `.layer-figcaption` from src/styles.css
 * rather than introducing a second treatment for the same object.
 */
export function mechanismFigure(id: string): string {
  const m = byId.get(id);
  if (!m) return "";
  return `
    <figure class="layer-figure" id="mechanism-${m.id}">
      <div class="learning-video-scroll" tabindex="0" role="group" aria-label="Video; scroll sideways when enlarged"><video
        class="layer-video"
        src="${clip(m.stem)}"
        poster="${poster(m.stem)}"
        controls
        playsinline
        preload="none"
        aria-label="${m.title}: ${m.evidenceLabel}"
      ><track kind="captions" srclang="en" label="English — complete narration" src="${captions(m.stem)}" default></video></div>
      <button type="button" class="figure-full-size" data-video-enlarge aria-pressed="false">Enlarge video to original size</button>
      <figcaption class="layer-figcaption">
        <p class="layer-evidence">${evidenceBadge(m.evidence)}<span class="layer-status-note">${m.evidenceLabel}</span></p>
        <div class="mechanism-caption-prose"><p>${m.lead}</p>${sourceNote(m)}${legacyMediaNote()}${transcript(m)}</div>
      </figcaption>
    </figure>`;
}

/**
 * The spoken lines, closed by default.
 *
 * Native synchronized captions carry the full narration during playback.
 * This separate transcript also supports reading, searching and review without
 * playing the movie; the on-frame summaries alone do not contain every word.
 */
function transcript(m: MechanismAnimation): string {
  const spoken = mechanismNarration(m.stem);
  if (!spoken.length) return "";
  const lines = spoken.map((t) => `<li>${t}</li>`).join("");
  return `<details class="mechanism-transcript"><summary>Narration transcript \u00b7 ${spoken.length} lines</summary><ol>${lines}</ol></details>`;
}

function sourceNote(m: MechanismAnimation): string {
  const references: Record<string, SourceId[]> = {
    'dayside-reconnection': ['dungey'], 'chapman-layer': ['chapman'],
    'hf-skip-blackout': ['drap'], 'trapped-motion': ['convection', 'dst'],
    'eccentric-dipole-saa': ['igrf', 'local'], 'drag-orbit-decay': ['local'],
  };
  return m.sources.map((s) => `<p><em>${s}</em></p>`).join("")
    + `<p class="method-citation">Sources: ${sourceLinks(references[m.id] ?? [])}</p>`;
}

/**
 * The whole library, as a section for the space-weather learning track.
 *
 * Deliberately not a wall of text: each card is a question and two sentences,
 * because the animation is the explanation and the prose is only there to say
 * which question it answers.
 */
export function mechanismLibrarySection(): string {
  return `
    <section class="method-section" id="mechanism-library" aria-labelledby="mechanism-library-title">
      <div class="method-section-head">
        <p class="section-kicker">MECHANISM LIBRARY · ${countWordCap(MECHANISM_ANIMATIONS.length).toUpperCase()} THINGS NO CAMERA HAS FILMED</p>
        <h2 id="mechanism-library-title">Watch the mechanism instead of reading it</h2>
        <p>${countWordCap(MECHANISM_ANIMATIONS.length)} short animations of the steps this site had been asserting in words. Every one is drawn from the geometry or the formula named on the frame, the teaching geometry is <strong>schematic</strong>. Trapped motion is a composite: its closing Kyoto Dst trace is observed, while the motion is schematic. None of them is generated video.</p>
      </div>
      ${MECHANISM_ANIMATIONS.map(mechanismCard).join("")}
    </section>`;
}

function mechanismCard(m: MechanismAnimation): string {
  return `
    <article class="mechanism-entry">
      <p class="section-kicker">MECHANISM ${m.index} · ${m.runtime}</p>
      <h3>${m.title}</h3>
      <p class="mechanism-question">${m.question}</p>
      ${mechanismFigure(m.id)}
    </article>`;
}
